
diccionario = {
    "a" : "vbg ",
    "b" : "vvg ",
    "c" : "tyu ",
    "d" : "cal ",
    "e" : "old ",
    "f" : "cfg ",
    "g" : "opl ",
    "h" : "iyt ",
    "i" : "tac ",
    "j" : "gld ",
    "k" : "med ",
    "l" : "led ",
    "m" : "poi ",
    "n" : "tyg ",
    "ñ" : "eqb ",
    "o" : "igt ",
    "p" : "uto ",
    "q" : "lfr ",
    "r" : "nmk ",
    "s" : "rew ",
    "t" : "vfs ",
    "u" : "jkl ",
    "v" : "wqa ",
    "w" : "htd ",
    "x" : "fkl ",
    "y" : "slp ",
    "z" : "qpo ",
    "A" : "swq ",
    "B" : "cvb ",
    "C" : "mkj ",
    "D" : "xdf ",
    "E" : "poi ",
    "F" : "qwe ",
    "G" : "xcz ",
    "H" : "asd ",
    "I" : "lsd ",
    "J" : "tof ",
    "K" : "pof ",
    "L" : "hrt ",
    "M" : "sdn ",
    "N" : "lvh ",
    "Ñ" : "chw ",
    "O" : "ort ",
    "P" : "hfl ",
    "Q" : "sdm ",
    "R" : "lfh ",
    "S" : "lmf ",
    "T" : "aff ",
    "U" : "pfh ",
    "V" : "nis ",
    "W" : "ong ",
    "X" : "thu ",
    "Y" : "ani ",
    "Z" : "zsa ",
    " " : "0rt ",#Espacio
    "1" : "l ",
    "2" : "r ",
    "3" : "e ",
    "4" : "a ",
    "5" : "s ",
    "6" : "g ",
    "7" : "t ",
    "8" : "b ",
    "9" : "p ",
    "0" : "o ",
    

}

def traducir(msj):
    traslation = ""
    for letter in range(len(msj)):
        traslation = traslation + diccionario[msj[letter]]
    return traslation
